"""Adicionar itens no Pedido

Revision ID: 0c8d3a186bf9
Revises: c06d23eaaa0c
Create Date: 2025-10-15 18:37:18.817956

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c8d3a186bf9'
down_revision: Union[str, Sequence[str], None] = 'c06d23eaaa0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
